In [1]:
import pandas as pd

In [18]:
demos = pd.read_excel('data/all_homeless_abs_demo.csv_homeless_abs_demo.csv')

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'Under 12'

In [11]:
demos

                                                          Unnamed: 0_level_0  \
                                                          Unnamed: 0_level_1
NaN                                                                      SA4
Australia                                                                NaN
NaN                                                                      NaN
New South Wales                                                          NaN
NaN                                                           Capital Region
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                            Central Coast
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                             Central West
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                  Coffs Harbour - Grafton
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                       Far West and Orana
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                              Hunter Valley exc Newcastle
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                Illawarra
...                                                                      ...
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
Northern Territory                                                       NaN
NaN                                                                   Darwin
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                             Northern Territory - Outback
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
Australian Capital Territory                                             NaN
NaN                                             Australian Capital Territory
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
NaN                                                                      NaN
Source: Census of Population and Housing, 2011                           NaN
NaN                                                                      NaN
NaN                                                                      NaN
© Commonwealth of Australia 2018                                         NaN

                                                        Unnamed: 1_level_0  \
                                                        Unnamed: 1_level_1
NaN                                                                    SA3
Australia                                                              NaN
NaN                                                                    NaN
New South Wales                                                        NaN
NaN                                                                    NaN
NaN                                                        Goulburn - Yass
NaN                                                             Queanbeyan
NaN                                                        Snowy Mountains
NaN                                                            South Coast
NaN                                                                    NaN
NaN                                                                Gosford
NaN                                                                  Wyong
NaN                                                                    NaN
NaN                                                               Bathurst
NaN                                                         Lachlan Valley
NaN                                                       Lithgow - Mudgee
NaN                                                                 Orange
NaN                                                                    NaN
NaN                                                        Clarence Valley
NaN                                                          Coffs Harbour
NaN                                                                    NaN
NaN                                             Bourke - Cobar - Coonamble
NaN                                               Broken Hill and Far West
NaN                                                                  Dubbo
NaN                                                                    NaN
NaN                                                           Lower Hunter
NaN                                                               Maitland
NaN                                                          Port Stephens
NaN                                                           Upper Hunter
NaN                                                                    NaN
...                                                                    ...
NaN                                                    Burnie - Ulverstone
NaN                                                              Devonport
NaN                                                             West Coast
Northern Territory                                                     NaN
NaN                                                                    NaN
NaN                                                            Darwin City
NaN                                                         Darwin Suburbs
NaN                                                             Litchfield
NaN                                                             Palmerston
NaN                                                                    NaN
NaN                                                          Alice Springs
NaN                                                                 Barkly
NaN                                              Daly - Tiwi - West Arnhem
NaN                                                            East Arnhem
NaN                                                              Katherine
Australian Capital Territory                                           NaN
NaN                                                                    NaN
NaN                                                              Belconnen
NaN                                                       Cotter - Namadgi
NaN                                             Fyshwick - Pialligo - Hume
NaN                                                              Gungahlin
NaN                                                         North Canberra
NaN                                                         South Canberra
NaN                                                            Tuggeranong
NaN                                                           Weston Creek
NaN                                                                  Woden
Source: Census of Population and Housing, 2011                         NaN
NaN                                                                    NaN
NaN                                                                    NaN
© Commonwealth of Australia 2018                                       NaN

                                                                                   HOMELESS OPERATIONAL GROUP  \
                                               Persons living in improvised dwellings, tents, or sleeping out
NaN                                                                                           no.
Australia                                                                                    6810
NaN                                                                                           NaN
New South Wales                                                                              1920
NaN                                                                                            45
NaN                                                                                             9
NaN                                                                                            13
NaN                                                                                             3
NaN                                                                                            22
NaN                                                                                           128
NaN                                                                                            52
NaN                                                                                            72
NaN                                                                                            39
NaN                                                                                            16
NaN                                                                                             4
NaN                                                                                            13
NaN                                                                                             7
NaN                                                                                            66
NaN                                                                                            35
NaN                                                                                            32
NaN                                                                                            35
NaN                                                                                            25
NaN                                                                                             3
NaN                                                                                             7
NaN                                                                                            41
NaN                                                                                            24
NaN                                                                                             4
NaN                                                                                             5
NaN                                                                                             8
NaN                                                                                           100
...                                                                                           ...
NaN                                                                                            10
NaN                                                                                            22
NaN                                                                                             8
Northern Territory                                                                            841
NaN                                                                                           345
NaN                                                                                           203
NaN                                                                                            59
NaN                                                                                            39
NaN                                                                                            45
NaN                                                                                           494
NaN                                                                                           227
NaN                                                                                            40
NaN                                                                                            73
NaN                                                                                            25
NaN                                                                                           129
Australian Capital Territory                                                                   28
NaN                                                                                            28
NaN                                                                                             0
NaN                                                                                             0
NaN                                                                                             0
NaN                                                                                             0
NaN                                                                                            22
NaN                                                                                             3
NaN                                                                                             0
NaN                                                                                             0
NaN                                                                                             0
Source: Census of Population and Housing, 2011                                                NaN
NaN                                                                                           NaN
NaN                                                                                           NaN
© Commonwealth of Australia 2018                                                              NaN

                                                                                                    \
                                               Persons in supported accommodation for the homeless
NaN                                                                                           no.
Australia                                                                                   21258
NaN                                                                                           NaN
New South Wales                                                                              4921
NaN                                                                                           168
NaN                                                                                            51
NaN                                                                                            46
NaN                                                                                             0
NaN                                                                                            70
NaN                                                                                           147
NaN                                                                                            67
NaN                                                                                            78
NaN                                                                                           132
NaN                                                                                            81
NaN                                                                                             7
NaN                                                                                            11
NaN                                                                                            31
NaN                                                                                           120
NaN                                                                                            34
NaN                                                                                            88
NaN                                                                                            52
NaN                                                                                            38
NaN                                                                                             7
NaN                                                                                            14
NaN                                                                                           104
NaN                                                                                            19
NaN                                                                                            30
NaN                                                                                            23
NaN                                                                                            29
NaN                                                                                           336
...                                                                                           ...
NaN                                                                                           114
NaN                                                                                            49
NaN                                                                                             7
Northern Territory                                                                            578
NaN                                                                                           266
NaN                                                                                           118
NaN                                                                                           125
NaN                                                                                             0
NaN                                                                                            21